# -*- coding: utf-8 -*-
"""LoL_match_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaKzi90s13Gbbe3SNjGO5dphW6tFIWXC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""League of Legends Match Analysis Data"""

df = pd.read_csv("League_of_Legends_Data - Sheet1 - V1.csv")

df.head()
df.info()

# Create KDA column
df['KDA'] = (df['kills'] + df['assists']) / df['deaths'].replace(0, np.nan)
df.head()

"""This creates a new column showing the KDA conversions per player"""

# Convert game_duration to minutes
df['game_minutes'] = df['game_duration'].apply(lambda x: int(x.split(":")[0]) + int(x.split(":")[1])/60)

df.head()

df.describe()

# Count games by queue_type

df['queue_type'].value_counts()

# Visualizations (graph 1) Average Gold by Role

sns.barplot(data=df, x='role', y='gold_earned', hue='win_loss')

"""This shows the average gold_earned by role type based on win_loss"""

# Visualizations (graph 2) KDA distribution

sns.histplot(df['KDA'].dropna(), bins=15, kde=True)

"""This shows how common different KDA ranges are across the data collected in these games"""

# Visualizations (graph 3) win rates based on being blue or red side

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# There were extra spaces in the team column, that we must remove to get this graph to work

df['team'] = df['team'].str.strip()

# Calculate win rates for each team side (blue and red)
win_rates = df.groupby('team')['win_loss'].apply(lambda x: (x== 'win').mean()).reset_index()

plt.figure(figsize=(6,4))
sns.barplot(x='team', y='win_loss', hue='team', data=win_rates, palette={'blue':'#4C72B0', 'red':'#D32F2F'},
    dodge=False) # this helps keep a single bar per team side
plt.ylim(0,1)
plt.ylabel('Win Rate')
plt.title('Win Rate by Team Side (blue or red)')
plt.show()

"""This graph shows win rates based on if players were blue or red side starting"""

# create a first blood win column
# players who got first blood AND won

df['first_blood_win'] = (df['first_blood'] == 'yes') & (df['win_loss'] == 'win')
df.head()

"""This creates a new column for players who got first blood AND won their game"""

# Group by role and summarize
role_fb_stats = df[df['first_blood'] == 'yes'].groupby('role').agg(
    first_blood_count=('first_blood', 'count'),
    wins_with_fb=('first_blood_win', 'sum')
)

# Win rate when getting first blood
role_fb_stats['win_rate'] = role_fb_stats['wins_with_fb'] / role_fb_stats['first_blood_count']

role_fb_stats

"""This shows which roles get first blood, how often they win if they get first blood, and their win rate"""

# Visualization (graph 4) First Blood by Role & Win Rates When Getting First Blood

import matplotlib.pyplot as plt

role_fb_stats['win_rate'].plot(kind='bar', color='purple', edgecolor='black')
plt.ylabel('Win Rate When Getting First Blood')
plt.title('First Blood by Role')
plt.ylim(0,1)
plt.show()

"""This shows which roles are most effective at converting first blood into a win"""

# Count how many times each champion was played in each role

champ_role_counts = df.groupby(['champion', 'role']).size().reset_index(name='count')

champ_role_counts

"""This shows how many champions were picked in each role"""

# Visualizations (graph 5) Show which champions are the most picked per role

import pandas as pd
import matplotlib.pyplot as plt

top_champions = df.groupby(['champion', 'role']).size().reset_index(name='count')

top_per_role = top_champions.loc[top_champions.groupby('role')['count'].idxmax()]

plt.figure(figsize=(8,5))
plt.bar(top_per_role['role'], top_per_role['count'], color='gold')
for i, row in top_per_role.iterrows():
  plt.text(row['role'], row['count']+0.2, row['champion'], ha='center', fontsize=9)
plt.ylabel('Times Picked')
plt.title('Most Popular Champions Per Role')
plt.show()

"""This graph shows the most popular champions by pick rates, per role"""